pipeline:
  projectIdentifier: krishikasingh
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: pysampleconnector
        build: <+input>
  stages:
    - stage:
        name: build test and run
        identifier: build_test_and_run
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Code compile
                  identifier: Code_compile
                  spec:
                    connectorRef: docker_Quickstart
                    image: python:3.10.6-alpine
                    shell: Sh
                    command: python -m compileall ./
              - step:
                  type: Run
                  name: Create image
                  identifier: Create_image
                  spec:
                    connectorRef: docker_Quickstart
                    image: alpine
                    shell: Sh
                    command: |-
                      echo <+stage.repeat.item>
                      touch pythondockerfile_<+strategy.iteration>
                      cat > pythondockerfile_<+strategy.iteration> <<- EOM
                      FROM python:<+stage.repeat.item>
                      WORKDIR /py-sample-proj
                      ADD . /py-sample-proj
                      RUN pip install -r requirements.txt
                      CMD ["python" , "app.py"]
                      EOM
                      cat pythondockerfile_<+strategy.iteration>
                  failureStrategies: []
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push an image to docker registry
                  identifier: Build_and_Push_an_image_to_docker_registry
                  spec:
                    connectorRef: <+input>
                    repo: <+input>
                    tags:
                      - <+stage.repeat.item>
                    dockerfile: pythondockerfile_<+strategy.iteration>
          infrastructure:
            type: KubernetesHosted
            spec:
              identifier: k8s-hosted-infra
        strategy:
          repeat:
            items:
              - 3.10.6-alpine
              - 3.10.4-alpine
          maxConcurrency: 2
    - stage:
        name: Integration test
        identifier: Integration_test
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            useFromStage: build_test_and_run
          execution:
            steps:
              - step:
                  type: Background
                  name: "python server "
                  identifier: python_server
                  spec:
                    connectorRef: <+input>
                    image: krishi0408/pythonsample:<+stage.repeat.item>
                    shell: Sh
                  description: "server connection "
                  failureStrategies: []
              - step:
                  type: Run
                  name: "test connection to server "
                  identifier: test_connection_to_server
                  spec:
                    connectorRef: <+input>
                    image: curlimages/curl:7.73.0
                    shell: Sh
                    command: |-
                      sleep 10
                      curl localhost:5000
        strategy:
          repeat:
            items:
              - 3.10.6-alpine
              - 3.10.4-alpine
          maxConcurrency: 2
  identifier: CIPythonQuickstart_Matrix
  name: "CI-Python-Quickstart - Matrix "
