kind: pipeline
type: docker
name: build test and run 

steps:
- name: run 
  image: python:3.10.6-alpine
  commands: 
  - python -m compileall ./
  
- name: en
  image: alpine
  commands:
  - echo hello world

