kind: pipeline
type: docker
name: build test and run 

steps:
- name: run 
  image: python:3.10.6-alpine
  commands: 
  - python -m compileall ./
  
- name: create docker file  
  image: alpine
  commands:
  -  touch pythondockerfile
     cat > pythondockerfile <<- EOM
     FROM python:3.10.6-alpine
     WORKDIR /python-pipeline-samples
     ADD . /python-pipeline-samples
     RUN pip install -r requirements.txt
     CMD ["python3" , "./app.py"]
     EOM
     cat pythondockerfile

  
- name: build and push to docker registry 
  image: plugins/docker
  settings:
    username: krishi0408
    password: Krishika@123
    repo: krishi0408/pythonsample
    tags: latest
---
kind: pipeline
type: docker
name: integration test 

steps:
- name: python-server
  image: krishi0408/pythonsample
  commands: 
  - python3 ./app.py

services:
- name: python-services
  image: krishi0408/pythonsample

